### ISSUE TITLE
npm run dev not working on use-modules branch.

### ISSUE THREAD

**Issue by Gnorshk** [Gnorshk/typologywebsite#6]
@zhex900 I merged the pull request into the use-modules branch and now, when I try to run it, It gives me errors which I can't make sense of.
Here is the terminal message:
![image](https://user-images.githubusercontent.com/65100907/89856405-8b9f9180-dbdc-11ea-8936-6712c532f8fd.png)
And here is the debug log:
![image](https://user-images.githubusercontent.com/65100907/89856700-5e071800-dbdd-11ea-9a6e-b40200b6daf9.png)

**Comment by zhex900** [comment]
slack

**Comment by Gnorshk** [comment]
I ran npm install, it works now
